// ─────────────────────────────────────────────────────────────────
//  Trollpick.GG — Liste des champions par rôle
//  Modifie ce fichier pour mettre à jour les champions
//  sur le site ET sur l'overlay en même temps.
// ─────────────────────────────────────────────────────────────────

const DEFAULT_CHAMPIONS = {
  TOP: ['Aatrox','Ahri','Akali','Akshan','Ambessa','Anivia','Aurelion Sol','Aurora','Azir','Bel\'Veth','Brand','Briar','Camille','Cassiopeia','Cho\'Gath','Darius','Diana','Dr.Mundo','Ekko','Elise','Fiddlesticks','Fiora','Fizz','Galio','Gangplank','Garen','Gnar','Gragas','Graves','Gwen','Heimerdinger','Hwei','Illaoi','Irelia','Ivern','Jax','Jayce','K\'Sante','Kalista','Karma','Kayle','Kayn','Kennen','Kled','LeeSin','Lillia','Lissandra','Malphite','Malzahar','Maokai','Master Yi','Mordekaiser','Morgana','Naafiri','Nasus','Neeko','Nidalee','Nocturne','Olaf','Ornn','Pantheon','Poppy','Qiyana','Quinn','Rammus','Rek\'Sai','Renekton','Rengar','Riven','Rumble','Ryze','Sejuani','Senna','Sett','Shaco','Shen','Shyvana','Singed','Sion','Skarner','Smolder','Swain','Sylas','Syndra','Tahm Kench','Talon','Teemo','Trundle','Tryndamere','Twisted Fate','Udyr','Urgot','Varus','Vayne','Veigar','Vi','Viego','Viktor','Vladimir','Volibear','Warwick','Wukong','Xin Zhao','Yasuo','Yone','Yorick','Zaahen','Zac','Zed'],
  JUNGLE: ['Aatrox','Ambessa','Amumu','Bel\'Veth','Brand','Briar','Camille','Cho\'Gath','Darius','Diana','Dr.Mundo','Ekko','Elise','Evelynn','Fiddlesticks','Fizz','Gragas','Graves','Gwen','Hecarim','Ivern','Jarvan IV','Jax','Jayce','Karthus','Kayn','Kha\'Zix','Kindred','LeeSin','Lillia','Malphite','Maokai','Master Yi','Mordekaiser','Morgana','Naafiri','Nasus','Neeko','Nidalee','Nocturne','Nunu','Olaf','Pantheon','Poppy','Qiyana','Rammus','Rek\'Sai','Rengar','Rumble','Sejuani','Shaco','Shen','Shyvana','Sion','Skarner','Sylas','Taliyah','Talon','Teemo','Trundle','Tryndamere','Twitch','Udyr','Vayne','Vi','Viego','Volibear','Warwick','Wukong','Xin Zhao','Yorick','Zaahen','Zac','Zed','Zeri','Zyra'],
  MID: ['Aatrox','Ahri','Akali','Akshan','Ambessa','Anivia','Annie','Aurelion Sol','Aurora','Azir','Brand','Briar','Camille','Cassiopeia','Cho\'Gath','Corki','Diana','Dr.Mundo','Draven','Ekko','Elise','Ezreal','Fiddlesticks','Fizz','Galio','Gangplank','Garen','Gragas','Gwen','Heimerdinger','Hwei','Irelia','Ivern','Jayce','Kai\'Sa','Karma','Karthus','Kassadin','Katarina','Kayle','Kennen','Kindred','Kled','Kog\'Maw','Leblanc','Lissandra','Lucian','Lux','Malphite','Malzahar','Mel','Mordekaiser','Morgana','Naafiri','Nasus','Neeko','Nidalee','Nocturne','Nunu','Olaf','Orianna','Ornn','Pantheon','Pyke','Qiyana','Quinn','Rakan','Renekton','Riven','Rumble','Ryze','Sejuani','Sett','Shen','Singed','Sion','Smolder','Swain','Sylas','Syndra','Seraphine','Tahm Kench','Taliyah','Talon','Teemo','Tristana','Tryndamere','Twisted Fate','Twitch','Varus','Vayne','Veigar','Vel\'Koz','Vex','Viego','Viktor','Vladimir','Xerath','Xin Zhao','Yasuo','Yone','Yorick','Zaahen','Zac','Zed','Zeri','Ziggs','Zilean','Zoe','Zyra','Wukong'],
  ADC: ['Akshan','Anivia','Annie','Aphelios','Ashe','Aurelion Sol','Azir','Brand','Caitlyn','Cassiopeia','Cho\'Gath','Corki','Draven','Ezreal','Heimerdinger','Hwei','Jhin','Jinx','Kai\'Sa','Kalista','Karthus','Katarina','Kindred','Kog\'Maw','Lucian','Lux','Malzahar','Mel','Miss Fortune','Nilah','Quinn','Rengar','Samira','Senna','Sion','Sivir','Smolder','Swain','Syndra','Seraphine','Tahm Kench','Taliyah','Tristana','Twisted Fate','Twitch','Varus','Vayne','Veigar','Vel\'Koz','Viktor','Vladimir','Xayah','Xerath','Yasuo','Yunara','Zeri','Ziggs','Zyra'],
  SUPPORT: ['Alistar','Amumu','Anivia','Annie','Ashe','Bard','Blitzcrank','Brand','Braum','Camille','Cho\'Gath','Elise','Fiddlesticks','Galio','Gragas','Heimerdinger','Hwei','Ivern','Janna','Karma','Leblanc','LeeSin','Leona','Lissandra','Lulu','Lux','Malphite','Maokai','Mel','Milio','Miss Fortune','Morgana','Nami','Nautilus','Neeko','Nidalee','Nunu','Ornn','Pantheon','Poppy','Pyke','Rakan','Rammus','Rell','Renata','Sejuani','Senna','Sett','Shaco','Shen','Sion','Skarner','Sona','Soraka','Swain','Sylas','Seraphine','Tahm Kench','Taliyah','Taric','Teemo','Thresh','Trundle','Twitch','Veigar','Vel\'Koz','Vex','Xerath','Yuumi','Zac','Ziggs','Zilean','Zoe','Zyra'],
};
