// ─────────────────────────────────────────────────────────────────
//  Trollpick.GG — Liste des champions par rôle
//  Modifie ce fichier pour mettre à jour les champions
//  sur le site ET sur l'overlay en même temps.
// ─────────────────────────────────────────────────────────────────

const DEFAULT_CHAMPIONS = {
  TOP: ['Aatrox','Akali','Akshan','Ambessa','Anivia','Annie','Aurelion Sol','Aurora','Azir','Brand','Briar','Camille','Cassiopeia',"Cho'Gath",'Darius','Dr. Mundo','Fiddlesticks','Fiora','Galio','Gangplank','Garen','Gnar','Gragas','Gwen','Heimerdinger','Illaoi','Irelia','Ivern','Jax','Jayce','Kalista','Karthus','Kassadin','Kayn','Kayle','Kennen','Kled',"K'Santé",'Lissandra','Malphite','Malzahar','Maokai','Maître Yi','Mordekaiser','Naafiri','Nasus','Olaf','Ornn','Pantheon','Poppy','Quinn','Rek'Sai','Renekton','Rengar','Riven','Rumble','Ryze','Sejuani','Sett','Shen','Singed','Sion','Skarner','Smolder','Swain','Sylas','Tahm Kench','Teemo','Trundle','Tryndamere','Twisted Fate','Udyr','Urgot','Varus','Vayne','Vladimir','Volibear','Warwick','Wukong','Xin Zhao','Yasuo','Yone','Yorick','Zac','Zaahen','Zilean'],
  JUNGLE: ['Aatrox','Ambessa',"Bel'Veth",'Briar',"Cho'Gath",'Darius','Diana','Dr. Mundo','Ekko','Elise','Evelynn','Fizz','Fiddlesticks','Gragas','Graves','Gwen','Hecarim','Ivern','Jarvan IV','Jax','Jayce','Karthus','Kayn',"Kha'Zix",'Kindred','Lee Sin','Lillia','Maître Yi','Malphite','Maokai','Mordekaiser','Naafiri','Nasus','Nidalee','Nocturne','Nunu et Willump','Olaf','Pantheon','Poppy','Qiyana','Quinn','Rammus',"Rek'Sai",'Rengar','Riven','Rumble','Sejuani','Shaco','Shen','Shyvana','Singed','Sion','Skarner','Sylas','Taliyah','Talon','Teemo','Trundle','Tryndamere','Twitch','Udyr','Vi','Viego','Volibear','Warwick','Wukong','Xin Zhao','Zac','Zed','Zaahen','Zyra'],
  MID: ['Ahri','Akali','Akshan','Ambessa','Anivia','Annie','Aurelion Sol','Aurora','Azir','Brand','Briar','Cassiopeia',"Cho'Gath",'Corki','Diana','Ekko','Fizz','Galio','Gangplank','Garen','Gragas','Gwen','Heimerdinger','Hwei','Irelia','Jayce','Karthus','Kassadin','Katarina','Kayle','Kennen','Kled',"Kog'Maw",'LeBlanc','Lissandra','Lux','Malphite','Malzahar','Mel','Morgana','Naafiri','Nasus','Neeko','Nunu et Willump','Orianna','Pantheon','Qiyana','Quinn','Renekton','Riven','Rumble','Ryze','Singed','Sion','Smolder','Swain','Sylas','Syndra','Taliyah','Talon','Tristana','Tryndamere','Twisted Fate','Varus','Veigar',"Vel'Koz",'Vex','Viktor','Vladimir','Xerath','Xin Zhao','Yasuo','Yone','Yorick','Zed','Ziggs','Zilean','Zoé','Zyra'],
  ADC: ['Aphelios','Ashe','Aurelion Sol','Akshan','Brand','Caitlyn','Cassiopeia','Corki','Draven','Ezreal','Heimerdinger','Hwei','Jhin','Jinx','Kai\'Sa','Kalista','Karthus','Katarina',"Kog'Maw",'Lucian','Mel','Miss Fortune','Nilah','Samira','Senna','Séraphine','Sivir','Smolder','Swain','Syndra','Teemo','Tristana','Twitch','Varus','Veigar',"Vel'Koz",'Vayne','Vladimir','Xayah','Xerath','Yasuo','Yunara','Zeri','Ziggs'],
  SUPPORT: ['Alistar','Amumu','Anivia','Annie','Ashe','Aurelion Sol','Bard','Blitzcrank','Braum','Camille','Cho\'Gath','Fiddlesticks','Galio','Gragas','Heimerdinger','Hwei','Ivern','Janna','Jarvan IV','Karma','Kennen','LeBlanc','Leona','Lissandra','Lulu','Lux','Maokai','Malphite','Mel','Milio','Morgana','Nami','Nautilus','Neeko','Nidalee','Nunu et Willump','Pantheon','Poppy','Pyke','Rakan','Rammus','Rell','Renata Glasc','Séraphine','Shaco','Shen','Singed','Sion','Skarner','Sona','Soraka','Swain','Sylas','Tahm Kench','Taliyah','Taric','Teemo','Thresh','Twitch','Twisted Fate','Veigar','Vel\'Koz','Xerath','Yuumi','Zac','Zilean','Ziggs','Zoé','Zyra'],
};
